name: Publish Node.js packages to npmjs.com
# The version in package.json must match the tag that triggered the workflow.
# For example, version in package.json is 0.1.12 and the tag that triggered must be v0.1.12.
on:
    push:
        tags:
            - v*.*.*
jobs:

    check:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: get-npm-version
          id: package-version
          uses: martinbeentjes/npm-get-version-action@master

        - name: Checks whether the tag is the same as the version ignoring the begin
          if: endsWith(github.ref, steps.package-version.outputs.current-version) != true
          run: 'echo "Tag is different from the new version" && exit 1'

    publish-npnjs:
        needs: check
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                node-version: [10.x]
        steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: npm install, build, and test
          run: |
            npm ci
            npm run build --if-present
            npm test
            npm run check-licenses

        - name: Set registry to npmjs.com
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: 'https://registry.npmjs.org'

        - name: Publish to npmjs.com
          run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}